# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "journala"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Robert Kaufman"]
  s.date = "2011-11-25"
  s.description = "a library that reads and write ledger format ledger files"
  s.email = "rob.m.kaufman@gmail.com"
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.txt",
    "Rakefile",
    "VERSION",
    "journala.gemspec",
    "lib/journala.rb",
    "lib/journala/entry.rb",
    "lib/journala/journal.rb",
    "lib/journala/row.rb",
    "lib/journala/value.rb"
  ]
  s.homepage = "http://github.com/kirkland/journala"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "inspired by ledger"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

